# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 14:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('key', models.CharField(max_length=1024)),
                ('secret', models.CharField(max_length=1024)),
                ('rsa', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=1024)),
                ('upload_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
                ('download_count', models.IntegerField(default=0)),
                ('apply_count', models.IntegerField(default=0)),
                ('is_enable', models.BooleanField(default=False)),
                ('is_gray', models.BooleanField(default=False)),
                ('pool_size', models.IntegerField(default=0)),
                ('patch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Patch')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.App')),
            ],
        ),
        migrations.AddField(
            model_name='patch',
            name='version_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Version'),
        ),
        migrations.AddField(
            model_name='app',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
        migrations.AddField(
            model_name='app',
            name='system_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.System'),
        ),
    ]
