# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('key', models.CharField(default=uuid.uuid4, max_length=1024)),
                ('secret', models.CharField(default=uuid.uuid4, max_length=1024)),
                ('rsa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=1024)),
                ('serial_number', models.IntegerField(default=1)),
                ('download_url', models.URLField()),
                ('size', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('download_count', models.IntegerField(default=0)),
                ('apply_count', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(0, 'Waiting'), (1, 'Released'), (2, 'Stoped'), (3, 'PreReleased'), (4, 'Deleted')], default=0)),
                ('pool_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.App')),
            ],
        ),
        migrations.AddField(
            model_name='patch',
            name='version_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Version'),
        ),
        migrations.AddField(
            model_name='app',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
        migrations.AddField(
            model_name='app',
            name='system_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.System'),
        ),
    ]
