# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='local_url',
            field=models.FileField(blank=True, upload_to='./upload/'),
        ),
    ]
