# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170817_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='pool_size',
            field=models.BigIntegerField(default=9223372036854775807),
        ),
    ]
