# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170821_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together=set([('category_id', 'system_id', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('app_id', 'name')]),
        ),
    ]
