# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170805_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
