# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170824_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='md5sum',
            field=models.CharField(default='', max_length=32),
        ),
    ]
