# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170805_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patch',
            old_name='download_url',
            new_name='local_url',
        ),
        migrations.AddField(
            model_name='patch',
            name='remote_url',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
