# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170818_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Wait'), (1, 'Release'), (2, 'Stop'), (3, 'Gary')], default=0),
        ),
    ]
