# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170818_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='is_gray',
        ),
    ]
