# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_patch_is_gray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Waiting'), (1, 'Released'), (2, 'Stoped'), (3, 'PreReleased'), (4, 'Deleted')], default=0),
        ),
    ]
