# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170806_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='rsa',
            field=models.TextField(),
        ),
    ]
