# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170806_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='local_url',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='remote_url',
        ),
        migrations.AddField(
            model_name='patch',
            name='download_url',
            field=models.URLField(default='http://'),
        ),
    ]
