# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170806_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='download_url',
            field=models.URLField(),
        ),
    ]
