# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170806_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='release',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
