# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170807_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='secret',
            field=models.CharField(default=uuid.uuid4, max_length=1024),
        ),
    ]
