# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170805_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='name',
        ),
        migrations.AddField(
            model_name='patch',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patch',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
