# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170805_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='release',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
