# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170805_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
