# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170805_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='apply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='release',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
