# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170805_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='is_gray',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='release',
            name='pool_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='release',
            name='is_enable',
            field=models.BooleanField(default=False),
        ),
    ]
