# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170805_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='version_id',
        ),
    ]
